export const services = {
  linguagem: {
    order: 1,
    name: 'Avaliação Fonoaudiológica',
    title: 'Avaliação Diagnóstica de Qualidade',
    text: 'Na jornada do desenvolvimento infantil, cada criança é única e por isso, uma avaliação diagnóstica especializada é o ponto de partida crucial! Com ela, podemos desvendar desafios que podem estar impedindo seu filho de alcançar seu potencial. E é nesse momento que entra um plano de intervenção feito sob medida, projetado para fornecer o suporte exato que seu pequeno precisa para florescer e prosperar na vida.',
    firstListItem: 'Processo diagnóstico ',
    secondListItem: 'Avaliação Clínica',
    thirdListItem: 'Utilização de protocolos validados',
    image: '/avaliacao-diagnostica.webp',
    alt: 'Fonoaudióloga Ana Nascimento no consultório em Jaraguá do Sul.',
  },
  social: {
    order: 2,
    name: 'Terapia Fonoaudiológica',
    title: 'Intervenção Fonoaudióloga em Jaraguá do Sul',
    text: 'Na busca de uma comunicação mais clara e eficaz, oferecerei intervenção fonoaudiológica personalizada, centrada no desenvolvimento das habilidades de fala e linguagem de cada criança, com o objetivo de auxiliar o seu filho a alcançar novos patamares em sua jornada para uma comunicação mais fluida e confiante.',
    firstListItem: 'Planejamento de Intervenção Individual',
    secondListItem: 'Apoio e orientação para os pais',
    thirdListItem: 'Atendimentos interativos e lúdicos',
    image: '/intervencao-fonoaudiologa.webp',
    alt: 'Mulher em sala representando Intervenção Fonoaudiológica com atendimento personalizado e suporte para os pais em Jaraguá do Sul.',
  },
  fonoaudiológico: {
    order: 3,
    name: 'Avaliação e Diagnóstico Fonoaudiológico',
    title: 'Avaliação e Diagnóstico Fonoaudiológico',
    text: 'A avaliação fonoaudiológica detalhada é o primeiro passo para identificar dificuldades na fala, linguagem, audição ou motricidade orofacial. Com base nessa análise, traçamos um plano de intervenção personalizado para atender às necessidades do paciente.',
    firstListItem: '',
    secondListItem: '',
    thirdListItem: '',
    image: '/intervencao-fonoaudiologa.webp',
    alt: '',
  },
  leitura: {
    order: 4,
    name: 'Linguagem',
    title: 'Terapia de Linguagem',
    text: 'Auxílio no desenvolvimento da comunicação oral, promovendo melhor interação social e desenvolvimento infantil. Ideal para crianças com atraso na fala, dificuldades na compreensão e expressão da linguagem.',
    firstListItem: '',
    secondListItem: '',
    thirdListItem: '',
    image: '/intervencao-fonoaudiologa.webp',
    alt: '',
  },
  fala: {
    order: 5,
    name: 'Fala',
    title: 'Terapia de Fala',
    text: 'Intervenção para dificuldades na pronúncia e organização dos sons da fala, como trocas de fonemas, além do tratamento de transtornos motores da fala.',
    firstListItem: '',
    secondListItem: '',
    thirdListItem: '',
    image: '/intervencao-fonoaudiologa.webp',
    alt: '',
  },
  gagueira: {
    order: 6,
    name: 'Gagueira',
    title: 'Terapia para Gagueira',
    text: 'Atendimento especializado para crianças que apresentam gagueira, ajudando a tornar a fala mais fluida e reduzindo impactos emocionais associados à comunicação.',
    firstListItem: '',
    secondListItem: '',
    thirdListItem: '',
    image: '/intervencao-fonoaudiologa.webp',
    alt: '',
  },
  Orofacial: {
    order: 7,
    name: 'Motricidade Orofacial',
    title: 'Terapia de Motricidade Orofacial',
    text: 'Tratamento para dificuldades na mastigação, deglutição, respiração e uso adequado dos músculos da face e boca.',
    firstListItem: '',
    secondListItem: '',
    thirdListItem: '',
    image: '/intervencao-fonoaudiologa.webp',
    alt: '',
  },
  criancas: {
    order: 8,
    name: 'Atendimento a Crianças com Condições Específicas',
    title: 'Atendimento a Crianças com Condições Específicas',
    text: 'Transtorno do Espectro Autista (TEA), Síndrome de Down, Atraso no Desenvolvimento da Fala, Transtornos Motores da Fala, Transtorno do Desenvolvimento Intelectual, Outras condições que impactam a comunicação',
    firstListItem: '',
    secondListItem: '',
    thirdListItem: '',
    image: '/intervencao-fonoaudiologa.webp',
    alt: '',
  },
};

export type ServicesType = keyof typeof services;
